feat(rabbit)[OK-284] Add RabbitMQ microservice for handling mailing system with proxy client
OBELISK-TEAM/OBELISK pull request #176
Opened 2024-11-01 13:08 UTC by marcepanowyy

2024-11-01 15:37 UTC, Wajktor13 requested changes

2024-11-01 15:37 UTC, Wajktor13 commented on docker-compose.yml
> +      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
```suggestion
      - RABBITMQ_USER
      - RABBITMQ_PASSWORD
```

2024-11-01 15:37 UTC, Wajktor13 commented on docker-compose.yml
>    mongo:
```suggestion
    environment:
      - SERVER_HOST
      - SERVER_PORT
      - SOCKET_GW_PORT
      - RABBITMQ_HOST
      - RABBITMQ_PORT
      - RABBITMQ_QUEUE
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - DB_HOST=mongo
      - DB_PORT
      - JWT_SECRET
      - JWT_EXPIRES_IN
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
      - GOOGLE_CALLBACK_URL
      - MAILING_HOST
      - MAILING_PORT
      - MAILING_SECURE
      - MAILING_USER
      - MAILING_PASS

  mongo:
```

2024-11-01 15:37 UTC, Wajktor13 commented on server/src/config/mogo.config.ts
wrong name

2024-11-01 17:02 UTC, marcepanowyy commented on server/src/config/mogo.config.ts
fixed

2024-11-01 17:02 UTC, marcepanowyy commented on docker-compose.yml
>    mongo:
fixed

2024-11-01 17:02 UTC, marcepanowyy commented on docker-compose.yml
> +      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
fixed

2024-11-01 17:28 UTC, Wajktor13 approved these changes, later dismissed

2024-11-02 11:54 UTC, Wajktor13 approved these changes
This PR:

1. Dockerizes RabbitMQ, adds new envs for rabbit
2. Adds configs (mongo.config.ts, logger.config.ts, …)
3. Adds mailing module
4. Integrates mailing module with rest of the serve
5. Moves stuff between shared/interfaces/decorators
6. … something else?

~1k lines in ~40files.

There should be at least one separate PR for each of this points. Combining it all into one results in a huge cognitive load and makes the PR unreadable and impossible to review correctly.

2024-11-02 16:11 UTC, merged