feat(board)[OK-59] Implement board eraser
OBELISK-TEAM/OBELISK pull request #50
Opened 2024-08-16 19:24 UTC by Strattoss

The eraser has been implemented thanks to a published fabricjs [eraser mixin](https://github.com/fabricjs/fabric.js/blob/master/src/mixins/eraser_brush.mixin.ts). There is the EraserBrush description:

```
  /**
   * EraserBrush class
   * Supports selective erasing meaning that only erasable objects are affected by the eraser brush.
   * Supports **inverted** erasing meaning that the brush can "undo" erasing.
   *
   * In order to support selective erasing, the brush clips the entire canvas
   * and then draws all non-erasable objects over the erased path using a pattern brush so to speak (masking).
   * If brush is **inverted** there is no need to clip canvas. The brush draws all erasable objects without their eraser.
   * This achieves the desired effect of seeming to erase or unerase only erasable objects.
   * After erasing is done the created path is added to all intersected objects' `eraser` property.
   *
   * In order to update the EraserBrush call `preparePattern`.
   * It may come in handy when canvas changes during erasing (i.e animations) and you want the eraser to reflect the changes.
   *
   * @tutorial {@link http://fabricjs.com/erasing}
   * @class fabric.EraserBrush
   * @extends fabric.PencilBrush
   * @memberof fabric
   */
```

Because the Eraser is a mixin, it isn't by default in the [npm fabric package](https://www.npmjs.com/package/fabric). That's why it has to be added into the application in the `"postinstall "` in the `package.json` file.

Other problematic thing is the fact that the EraserBrush class is not in the `@types/fabric` package so the TS is very unhappy, because it thinks that we create and use an instance of a class that hasn't been defined anywhere. That's why we have to write `// @ts-ignore` everywhere we use it.

2024-08-17 16:29 UTC, Strattoss commented
How it actually works in action:

https://github.com/user-attachments/assets/21d4d52e-8f64-4728-b906-0f4ef3b6971b

2024-08-18 10:47 UTC, Adam0s007 requested changes
There is an issue with the selection and drawing modes. When we add a new object to the canvas, the selection mode icon is no longer active. To address this, we could adjust our code by returning **isDrawingMode** in `useMenuData`. In `SidebarItem`, try modifying the `className` on the button like this:

```jsx
<button
  className={`flex items-center text-left text-gray-600 hover:bg-gray-200 p-2 rounded cursor-pointer ${
    activeItem === item.name ||
    (isDrawingMode && item.name === MenuAction.DrawingMode) ||
    (!isDrawingMode && item.name === MenuAction.SelectionMode)
      ? "bg-gray-200 text-black"
      : ""
  }`}
>
```

Consider adding a prop for `isDrawingMode` in `SidebarItem`, and then passing it from `BoardSidebar` in `Sidebar.tsx`. Finally, make sure to pass it through in `page.tsx` within the `board` folder. Additionally, when we select the eraser mode, the drawing mode becomes active as well. You can skip handling this for now. During the refactoring process, I'll change the isDrawingMode boolean type to something more descriptive, like canvasMode state, using an enum type with values such as
`draw`, `erase`, and `select`.

2024-08-18 14:23 UTC, Adam0s007 approved these changes

2024-08-18 14:23 UTC, Strattoss commented
Fix has been introduced.
As you've noticed, when a user chooses the eraser mode, the pencil icon will also be highlighted as if it was active.
Leaving it for now.

2024-08-18 14:24 UTC, merged